# /etc/nginx/sites-available/edu-portal
# ln -s /etc/nginx/sites-available/edu-portal /etc/nginx/sites-enabled/edu-portal

server {
    listen 80;
    server_name edu.rvnza.ru;

    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /var/www/edu-portal/app/static/;
        expires 7d;
    }
}
