name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to edu.rvnza.ru
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to server via SSH v2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          envs: DEPLOY_PATH
          script_stop: true
          script: echo "NEW SCRIPT VERSION 2" && echo "Path is $DEPLOY_PATH" && cd "$DEPLOY_PATH" && pwd && git log --oneline -1
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
